services:
    _defaults: { autowire: true, autoconfigure: true, public: true }


    # Download Athletenbiografie
    Markocupic\RszAthletenbiografieBundle\Docx\Athletenbiografie:
        arguments:
        - '%kernel.project_dir%'


